name: Build and push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Log to docker ### YamlMime:Hub
        uses: docker/login-action@v1
        with:
          username: ${{DATABASE_USERNAME}}
          password: ${{DATABASE_PASSWORD}}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file : docker/DockerFile.use
          push: true
          tags: vishnu2171/cicd:latest

      - name: Verify Pushed Image
        run: docker pull vishnu2171/cicd:latest
          
